import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import ScrollToTop from "./component/common/ScrollToTop";
import "./globals.css";
import ReduxProvider from "./redux/ReduxProvider";
import GlobalLoader from "./component/common/GlobalLoader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <GlobalLoader />
          {children}
        </ReduxProvider>
        <ScrollToTop />
      </body>
    </html>
  );
}
